try:
    pass
except NameError:
    pass
except Exception:
    pass
except BaseException:
    pass
else:
    pass
finally:    # произошел exception или нет finally выполняется ВСЕГДА
    pass



if True:
    pass
else:
    pass



while True:
    pass
else:
    pass



for i in []:
    pass
else:
    pass

